codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: '90...100'

  status:
    project:
      default:
        target: auto
        threshold: 50
        base: auto
    patch: off
    changes: yes

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: 'reach,diff,flags,tree'
  behavior: default
  require_changes: no

ignore:
  # Tested but not recognized by codecov
  - 'packages/ckb-sdk-rpc/src/index.ts'
